[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false